version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "oscarfonts/h2:latest"
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: "-ifNotExists"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"